version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: SimpleInjector.Integration.AspNetCore.Mvc
    versions:
    - 5.1.1
    - 5.2.0
  - dependency-name: SimpleInjector
    versions:
    - 5.2.1
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
